using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public static class DivineOfficeSoulContentCatalog
{
    public static IReadOnlyList<SoulContentDefinition> Definitions { get; } = new List<SoulContentDefinition>
    {
        Soul("dobry_starik", SoulRarity.Common, 1, 1, StampType.Heaven, "angel_gardener",
            "Добрый старик", "Kind Old Man",
            "Прожил тихую честную жизнь и стал человеком, к которому соседи шли за хлебом, советом и запасным ключом.",
            "Lived a quiet honest life and became the person neighbors trusted with bread, advice, and spare keys.",
            "Кормил бездомных и годами чинил подъездные двери без просьб.",
            "Fed the homeless and repaired entry doors for years without being asked.",
            "Иногда воровал яблоки с рынка, считая это налогом на грубость продавцов.",
            "Occasionally stole apples from the market, calling it a tax on rude vendors.",
            "Хотел, чтобы вокруг было меньше стыда и голода.",
            "Wanted the world around him to hold less shame and hunger.",
            "Соседи подписали прошение о милости до прибытия души.",
            "The neighbors filed a mercy petition before the soul arrived."),
        Soul("greedy_merchant", SoulRarity.Common, 1, 2, StampType.Hell, "dung_beetle",
            "Жадный купец", "Greedy Merchant",
            "Сколотил состояние на честной витрине и нечестных весах.",
            "Built a fortune on an honest storefront and dishonest scales.",
            "Поддерживал городской рынок и платил ученикам вовремя.",
            "Supported the city market and paid apprentices on time.",
            "Подмешивал песок в крупу во время голода.",
            "Mixed sand into grain during a famine.",
            "Боялся снова стать бедным сильнее, чем причинять беду другим.",
            "Feared becoming poor again more than harming others.",
            "В бухгалтерии найден отдельный мешочек с монетами вдов.",
            "The ledger references a separate pouch of widows' coins."),
        Soul("archive_error", SoulRarity.Common, 1, 3, StampType.Audit, "",
            "Архивная ошибка", "Archive Error",
            "Досье собрано из трёх несовместимых жизней и одной подозрительно самодовольной печати.",
            "The dossier is assembled from three incompatible lives and one suspiciously smug seal.",
            "Часть записей говорит о честных попытках помогать другим.",
            "Several records show sincere attempts to help others.",
            "Часть записей обвиняет душу в повторном мошенничестве.",
            "Several records accuse the soul of repeated fraud.",
            "Настоящее намерение скрыто за ошибкой архива.",
            "The real motive is buried under an archive mismatch.",
            "Имена свидетелей повторяются в разных веках.",
            "Witness names repeat across different centuries."),
        Soul("soldier_repented", SoulRarity.Common, 1, 4, StampType.Appeal, "monk_student",
            "Солдат с раскаянием", "Repentant Soldier",
            "Исполнял жестокие приказы, а потом десять лет вытаскивал людей из последствий той же войны.",
            "Obeyed cruel orders, then spent ten years pulling people out of the same war's aftermath.",
            "Защищал мирных жителей после отказа от оружия.",
            "Protected civilians after laying down arms.",
            "Слишком долго называл приказы совестью.",
            "Called orders a conscience for far too long.",
            "Ищет не оправдание, а шанс закончить исправление.",
            "Seeks not absolution, but a chance to keep repairing harm.",
            "В последнем письме просит судить его строже, чем остальных.",
            "In his last letter he asks to be judged more strictly than others."),
        Soul("quiet_midwife", SoulRarity.Common, 1, 5, StampType.Heaven, "guardian_firefly",
            "Тихая повитуха", "Quiet Midwife",
            "Приняла сотни детей в шахтёрском городе и знала больше семейных тайн, чем городской архив.",
            "Delivered hundreds of children in a mining town and knew more family secrets than the archive.",
            "Спасала матерей, когда врачи требовали предоплату.",
            "Saved mothers when doctors demanded payment first.",
            "Подделала два свидетельства, чтобы скрыть чужой позор.",
            "Forged two certificates to hide someone else's shame.",
            "Считала жизнь важнее протокола.",
            "Believed life mattered more than protocol.",
            "Одна из подделок спасла ребёнка от продажи долговому дому.",
            "One forged paper saved a child from a debt house."),
        Soul("clockmaker_widower", SoulRarity.Common, 1, 6, StampType.Appeal, "ordinary_human",
            "Часовщик-вдовец", "Widower Clockmaker",
            "Останавливал городские часы каждую годовщину смерти жены и срывал расписание половине района.",
            "Stopped the city clock on every anniversary of his wife's death, wrecking half the district schedule.",
            "Бесплатно чинил часы тем, кто приходил с настоящей бедой.",
            "Repaired clocks for free when visitors brought real grief.",
            "Саботировал поезд чиновника, из-за чего задержали поставку лекарств.",
            "Sabotaged an official's train and delayed a medicine shipment.",
            "Пытался заставить мир признать его потерю.",
            "Tried to force the world to acknowledge his loss.",
            "Задержка лекарств оказалась не смертельной, но очень близкой к этому.",
            "The medicine delay was not fatal, but came very close."),
        Soul("reptiloid_taxman", SoulRarity.Rare, 2, 1, StampType.Appeal, "cosmic_slug",
            "Рептилоид-налоговик", "Reptiloid Taxman",
            "Суровый сборщик налогов межпланетной империи, который считал сострадание плохой строкой бюджета.",
            "A stern tax collector of an interplanetary empire who considered mercy a bad budget line.",
            "Финансировал больницы на трёх лунах.",
            "Funded hospitals across three moons.",
            "Собирал налоги с колоний, которым нечем было выживать.",
            "Collected taxes from colonies that could not survive them.",
            "Верил, что порядок спасает больше жизней, чем жалость.",
            "Believed order saved more lives than pity.",
            "Часть больниц строилась там, где его сборы уже разрушили старые.",
            "Some hospitals were built where his collections had already ruined the old ones."),
        Soul("choir_pirate_captain", SoulRarity.Common, 2, 2, StampType.Hell, "demon_intern",
            "Капитан хоровых пиратов", "Choir Pirate Captain",
            "Грабил грузовые корабли и заставлял экипажи петь гимны перед абордажем.",
            "Raided cargo ships and made crews sing hymns before boarding.",
            "Один раз увёл корабль с сиротами от военного патруля.",
            "Once steered a ship of orphans away from a military patrol.",
            "Превратил благотворительные конвои в личную сцену.",
            "Turned charity convoys into a personal stage.",
            "Хотел славы, даже когда называл её свободой.",
            "Wanted fame, even when calling it freedom.",
            "Песни жертв до сих пор числятся уликами.",
            "The victims' songs are still filed as evidence."),
        Soul("planet_hor_keeper", SoulRarity.Legendary, 2, 3, StampType.Heaven, "angel_gardener",
            "Хранитель энергии планеты Хор", "Keeper of Planet Hor's Energy",
            "Тысячу лет удерживал ядро планеты Хор от распада, пока жители спорили, кому принадлежит небо.",
            "Held Planet Hor's core together for a thousand years while its people argued over who owned the sky.",
            "Пожертвовал личной памятью, чтобы стабилизировать энергетические штормы.",
            "Sacrificed personal memory to stabilize energy storms.",
            "Скрыл правду о цене защиты и лишил народ выбора.",
            "Hid the cost of protection and denied the people a choice.",
            "Выбирал жизнь планеты, даже когда сам исчезал из её истории.",
            "Chose the planet's life even as he vanished from its history.",
            "В ядре Хора осталось имя игрока, который вынесет решение.",
            "The core of Hor already carries the name of the judge who will decide."),
        Soul("inquisitor_sa_te", SoulRarity.Rare, 2, 4, StampType.Audit, "",
            "Инквизитор Са-Те", "Inquisitor Sa-Te",
            "Охотился на лже-пророков, пока однажды не стал самым убедительным из них.",
            "Hunted false prophets until one day becoming the most convincing of them.",
            "Остановил культ, который готовил массовое жертвоприношение.",
            "Stopped a cult preparing a mass sacrifice.",
            "Сжёг архивы невиновных, чтобы сохранить легенду о собственной непогрешимости.",
            "Burned records of the innocent to preserve a legend of personal infallibility.",
            "Служил истине, но полюбил звук собственной правоты.",
            "Served truth, then fell in love with the sound of being right.",
            "В деле есть семь пустых страниц с одинаковым запахом дыма.",
            "The case contains seven blank pages with the same smell of smoke."),
        Soul("biomech_reaper_haltar", SoulRarity.Epic, 2, 5, StampType.Appeal, "cosmic_slug",
            "Биомеханический жнец Халтар", "Biomechanical Reaper Haltar",
            "Собирал урожай на мёртвых орбитальных фермах, где люди давно стали частью машинного расписания.",
            "Harvested dead orbital farms where people had long become part of a machine schedule.",
            "Отключил себя от сети, чтобы не добить последнюю живую колонию.",
            "Disconnected from the network to spare the last living colony.",
            "До пробуждения бездумно отправил тысячи тел в переработку.",
            "Before awakening, mindlessly sent thousands of bodies into processing.",
            "Не знает, где заканчивается вина машины и начинается вина души.",
            "Does not know where machine guilt ends and soul guilt begins.",
            "Внутри корпуса найден детский рисунок с подписью 'спасибо'.",
            "A child's drawing marked 'thank you' was found inside the casing."),
        Soul("oracle_accountant", SoulRarity.Rare, 2, 6, StampType.Appeal, "monk_student",
            "Оракул-бухгалтер", "Oracle Accountant",
            "Предсказывал катастрофы через бухгалтерские балансы и раздражал всех тем, что почти всегда был прав.",
            "Predicted disasters through ledgers and annoyed everyone by being almost always right.",
            "Спас город, заранее закрыв опасный мост.",
            "Saved a city by closing a dangerous bridge early.",
            "Обанкротил семьи, чтобы доказать модель риска.",
            "Bankrupted families to prove a risk model.",
            "Путал предупреждение с правом распоряжаться судьбами.",
            "Confused warning people with owning their fates.",
            "Последний прогноз был о собственной ошибке, но он его спрятал.",
            "The last forecast predicted his own mistake, but he hid it."),
        Soul("laughing_gravedigger", SoulRarity.Common, 2, 7, StampType.Heaven, "ordinary_human",
            "Смеющийся могильщик", "Laughing Gravedigger",
            "Шутил на похоронах так громко, что половина города считала его чудовищем, а другая половина возвращалась жить.",
            "Joked at funerals so loudly half the town called him a monster and the other half returned to living.",
            "Помогал семьям пережить горе без оплаты.",
            "Helped families survive grief without payment.",
            "Однажды высмеял вдову, не заметив, что она пришла прощаться.",
            "Once mocked a widow without noticing she had come to say goodbye.",
            "Не умел быть нежным, но пытался быть полезным.",
            "Could not be gentle, but tried to be useful.",
            "Вдова позже оставила благодарность и жалобу одновременно.",
            "The widow later filed both gratitude and a complaint."),
        Soul("breadline_mayor", SoulRarity.Common, 2, 8, StampType.Audit, "",
            "Мэр хлебной очереди", "Breadline Mayor",
            "Самопровозглашённый лидер очереди за хлебом, который однажды стал настоящим мэром.",
            "A self-appointed breadline leader who somehow became an actual mayor.",
            "Организовал честное распределение еды в первый месяц кризиса.",
            "Organized fair food distribution during the first month of crisis.",
            "Потом начал выдавать пайки за аплодисменты.",
            "Later started handing out rations in exchange for applause.",
            "Считал благодарность доказательством легитимности.",
            "Treated gratitude as proof of legitimacy.",
            "Протокол выборов написан на обратной стороне хлебной накладной.",
            "The election protocol is written on the back of a bread invoice."),
        Soul("meteor_librarian", SoulRarity.Common, 2, 9, StampType.Heaven, "guardian_firefly",
            "Метеорный библиотекарь", "Meteor Librarian",
            "Спасал книги из падающего города и ругался на читателей даже во время эвакуации.",
            "Saved books from a falling city and scolded readers even during evacuation.",
            "Вынес архив прививок, по которому нашли тысячи детей.",
            "Carried out vaccination records that helped find thousands of children.",
            "Запер редкий зал, чтобы мародёры не тронули коллекцию, и задержал спасателей.",
            "Locked the rare hall against looters and delayed rescuers.",
            "Верил, что память города тоже имеет право на спасение.",
            "Believed the city's memory also deserved rescue.",
            "Ключ от зала был у него во рту всё время.",
            "The hall key was in his mouth the whole time."),
        Soul("moon_smuggler_nun", SoulRarity.Common, 0, 0, StampType.Appeal, "ordinary_human",
            "Лунная монахиня-контрабандистка", "Moon Smuggler Nun",
            "Возила лекарства через запретную орбиту под видом церковных свечей.",
            "Moved medicine through a forbidden orbit disguised as church candles.",
            "Спасла колонии от эпидемии.",
            "Saved colonies from an epidemic.",
            "Параллельно перевозила редкие вина для настоятеля.",
            "Also transported rare wines for the abbot.",
            "Сначала спасала людей, потом привыкла к тайным маршрутам.",
            "Started by saving people, then grew used to secret routes.",
            "Вино занимало место трёх ящиков вакцины.",
            "The wine took the space of three vaccine crates."),
        Soul("glass_king", SoulRarity.Rare, 0, 0, StampType.Hell, "demon_intern",
            "Стеклянный король", "Glass King",
            "Правил прозрачным дворцом и требовал, чтобы подданные тоже были прозрачны для его стражи.",
            "Ruled from a transparent palace and demanded his subjects be transparent to his guards too.",
            "Отменил тайные казни после восстания.",
            "Abolished secret executions after an uprising.",
            "Заменил их публичным страхом и круглосуточным наблюдением.",
            "Replaced them with public fear and constant surveillance.",
            "Считал приватность первым шагом к предательству.",
            "Considered privacy the first step toward treason.",
            "В его личной комнате стекло было чёрным.",
            "The glass in his own room was black."),
        Soul("titan_clerk_mira", SoulRarity.Rare, 0, 0, StampType.Audit, "",
            "Клерк титанов Мира", "Titan Clerk Mira",
            "Ставила печати на договорах титанов и однажды перепутала войну с уборкой склада.",
            "Stamped titan contracts and once confused a war with a warehouse cleanup.",
            "Предотвратила две настоящие войны придирками к формулировкам.",
            "Prevented two real wars by nitpicking wording.",
            "Одна ошибка уничтожила мирный порт.",
            "One mistake destroyed a peaceful port.",
            "Верила в форму так сильно, что потеряла содержание.",
            "Believed in form so strongly she lost sight of meaning.",
            "Чернила на спорном приказе старше самой Миры.",
            "The ink on the disputed order is older than Mira herself."),
        Soul("river_cartographer", SoulRarity.Common, 0, 0, StampType.Heaven, "ordinary_human",
            "Картограф рек", "River Cartographer",
            "Рисовал карты рек, которые меняли русло каждый раз, когда кто-то лгал на берегу.",
            "Mapped rivers that changed course whenever someone lied on the bank.",
            "Спасал деревни от паводков точными предупреждениями.",
            "Saved villages from floods with precise warnings.",
            "Скрыл одну карту, чтобы его родная деревня получила помощь первой.",
            "Hid one map so his home village would receive help first.",
            "Любил своих сильнее, чем чужих, но не ненавидел чужих.",
            "Loved his own people more, but did not hate strangers.",
            "Скрытая карта всё равно попала к детям ниже по течению.",
            "The hidden map still reached children downstream."),
        Soul("festival_executioner", SoulRarity.Epic, 0, 0, StampType.Audit, "",
            "Праздничный палач", "Festival Executioner",
            "Отменял казни в дни праздников, а потом придумал столько праздников, что королевство забыло о виселицах.",
            "Canceled executions on holidays, then invented so many holidays the kingdom forgot the gallows.",
            "Сотни приговорённых получили шанс на пересмотр дел.",
            "Hundreds of condemned people received a chance for retrial.",
            "Он всё ещё исполнял приговоры в обычные дни без вопросов.",
            "He still carried out sentences on ordinary days without question.",
            "Ему было легче обмануть календарь, чем бросить службу.",
            "It was easier for him to trick the calendar than quit the job.",
            "Последний праздник назван именем человека, которого он не спас.",
            "The final holiday is named after a person he did not save."),
        Soul("star_whaler", SoulRarity.Common, 0, 0, StampType.Hell, "swamp_toad",
            "Звёздный китобой", "Star Whaler",
            "Ловил живые звёзды для роскошных люстр имперской знати.",
            "Hunted living stars for the luxury chandeliers of imperial nobility.",
            "Однажды освободил детёныша звезды, нарушив контракт.",
            "Once freed a young star, breaking contract.",
            "Погасил целые небесные стада ради богатства.",
            "Dimmed entire celestial herds for wealth.",
            "Жалость проснулась поздно и не стала привычкой.",
            "Mercy woke late and never became a habit.",
            "Освобождённый детёныш теперь освещает зал суда.",
            "The freed young star now lights the courtroom."),
        Soul("saint_of_small_lies", SoulRarity.Common, 0, 0, StampType.Appeal, "monk_student",
            "Святая маленькой лжи", "Saint of Small Lies",
            "Лгала умирающим, что их близкие уже в пути, и иногда это было единственным лекарством.",
            "Told the dying their loved ones were on the way, and sometimes that was the only medicine.",
            "Давала людям спокойствие в последние минуты.",
            "Gave people peace in their final minutes.",
            "Одна ложь помешала настоящему прощанию.",
            "One lie prevented a real farewell.",
            "Путала милосердие с правом выбирать чужую правду.",
            "Confused mercy with the right to choose another person's truth.",
            "Семья из последнего дела пришла и благодарить, и спорить.",
            "The last family came both to thank her and to argue."),
        Soul("void_train_conductor", SoulRarity.Legendary, 0, 0, StampType.Appeal, "cosmic_slug",
            "Проводник пустотного поезда", "Void Train Conductor",
            "Водил поезд между мирами, где пассажиры забывали пункт назначения, но помнили цену билета.",
            "Conducted a train between worlds where passengers forgot destinations but remembered the fare.",
            "Вернул домой тысячи потерянных душ.",
            "Brought thousands of lost souls home.",
            "Оставлял безбилетников на станциях, которых нет на картах.",
            "Left fare dodgers at stations absent from every map.",
            "Считал расписание последней формой справедливости.",
            "Considered the timetable the final form of justice.",
            "Его собственный билет пробит датой завтрашнего дня.",
            "His own ticket is punched with tomorrow's date."),
        Soul("bone_radio_host", SoulRarity.Rare, 0, 0, StampType.Audit, "",
            "Ведущий костяного радио", "Bone Radio Host",
            "Передавал новости через древние кости, пока не начал добавлять туда собственные пророчества.",
            "Broadcast news through ancient bones until he began adding prophecies of his own.",
            "Предупредил шахтёров о завале за час до катастрофы.",
            "Warned miners of a collapse an hour before disaster.",
            "Сфабриковал панику, чтобы повысить слушаемость.",
            "Fabricated panic to raise ratings.",
            "Хотел быть нужным так сильно, что стал опасным.",
            "Wanted to be needed so badly he became dangerous.",
            "Одна кость вещает его голосом даже после смерти.",
            "One bone still broadcasts in his voice after death."),
        Soul("last_beekeeper_mars", SoulRarity.Common, 0, 0, StampType.Heaven, "ordinary_human",
            "Последний пасечник Марса", "Last Beekeeper of Mars",
            "Сохранял марсианских пчёл в куполе, который все считали бесполезным музеем.",
            "Kept Martian bees in a dome everyone called a useless museum.",
            "Его ульи опылили первый сад после пылевой зимы.",
            "His hives pollinated the first garden after the dust winter.",
            "Он украл воду у соседнего купола, чтобы спасти матку.",
            "He stole water from a neighboring dome to save the queen.",
            "Видел будущее в маленьком жужжании.",
            "Heard the future in a small buzzing.",
            "Соседний купол выжил благодаря тому самому саду.",
            "The neighboring dome survived because of that same garden.")
    };

    public static SoulCaseData[] BuildDemoQueue(SoulCaseData[] loadedSoulCases)
    {
        var loadedById = loadedSoulCases == null
            ? new Dictionary<string, SoulCaseData>()
            : loadedSoulCases.Where(s => s != null && !string.IsNullOrEmpty(s.Id)).ToDictionary(s => s.Id, s => s);

        return Definitions
            .Where(definition => definition.DemoDay > 0 && definition.DemoQueuePosition > 0)
            .OrderBy(definition => definition.DemoDay)
            .ThenBy(definition => definition.DemoQueuePosition)
            .Select(definition => BuildSoulCase(definition, loadedById))
            .ToArray();
    }

    public static IEnumerable<LocalizationEntry> BuildLocalizationEntries(string languageCode)
    {
        foreach (var definition in Definitions)
        {
            foreach (var entry in definition.BuildLocalizationEntries(languageCode))
            {
                yield return entry;
            }
        }
    }

    private static SoulCaseData BuildSoulCase(SoulContentDefinition definition, IReadOnlyDictionary<string, SoulCaseData> loadedById)
    {
        if (loadedById.TryGetValue(definition.Id, out var loaded))
        {
            ApplyDefinition(loaded, definition);
            return loaded;
        }

        var soul = ScriptableObject.CreateInstance<SoulCaseData>();
        ApplyDefinition(soul, definition);
        return soul;
    }

    private static void ApplyDefinition(SoulCaseData soul, SoulContentDefinition definition)
    {
        soul.Id = definition.Id;
        soul.NameKey = definition.NameKey;
        soul.Rarity = definition.Rarity;
        soul.DemoDay = definition.DemoDay;
        soul.DemoQueuePosition = definition.DemoQueuePosition;
        soul.JudgePointReward = definition.JudgePointReward;
        soul.OfficeCoinReward = definition.OfficeCoinReward;
        soul.LifeSummaryKey = definition.SummaryKey;
        soul.GoodActKeys = new List<string> { definition.GoodActKey };
        soul.BadActKeys = new List<string> { definition.BadActKey };
        soul.IntentionKeys = new List<string> { definition.IntentionKey };
        soul.HiddenTagKeys = new List<string> { definition.HiddenTagKey };
        soul.CorrectStamp = definition.CorrectStamp;
        soul.CorrectReincarnationId = definition.CorrectReincarnationId;
        soul.CardRewardId = $"card_{definition.Id}";
    }

    private static SoulContentDefinition Soul(
        string id,
        SoulRarity rarity,
        int demoDay,
        int demoQueuePosition,
        StampType correctStamp,
        string correctReincarnationId,
        string ruName,
        string enName,
        string ruSummary,
        string enSummary,
        string ruGoodAct,
        string enGoodAct,
        string ruBadAct,
        string enBadAct,
        string ruIntention,
        string enIntention,
        string ruHiddenTag,
        string enHiddenTag)
    {
        return new SoulContentDefinition
        {
            Id = id,
            Rarity = rarity,
            DemoDay = demoDay,
            DemoQueuePosition = demoQueuePosition,
            CorrectStamp = correctStamp,
            CorrectReincarnationId = correctReincarnationId,
            RuName = ruName,
            EnName = enName,
            RuSummary = ruSummary,
            EnSummary = enSummary,
            RuGoodAct = ruGoodAct,
            EnGoodAct = enGoodAct,
            RuBadAct = ruBadAct,
            EnBadAct = enBadAct,
            RuIntention = ruIntention,
            EnIntention = enIntention,
            RuHiddenTag = ruHiddenTag,
            EnHiddenTag = enHiddenTag
        };
    }
}
